#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged || (
    echo '❌❌❌ Failed to commit ❌❌❌
        Eslint check failed. Running yarn lint:fix for fixing your code🔨'
    false;
)

echo '✅✅✅ No errors...You can push your code now ✅✅✅'
